<?php 

require_once(dirname(__FILE__) .'/nprt.utils.inc');

function nprt_perm() {
  return array('access nprt', 'administer nprt');
} 

function nprt_menu(){
	$items = array();
	$items['raids'] = array(
		'title' => t('Raids'),
		'description' => 'Show Latest Loots.',
		'page callback' => 'nprt_player_items_page',
		'access arguments' => array('access nprt'),
		'type' => MENU_NORMAL_ITEM,
		'file'	=> 'nprt.pages.inc',
		
	);
	$items['raids/items'] = array(
	    'title' => t('Loots'),
		'description' => 'Show Latest Loots.',
		'type' => MENU_DEFAULT_LOCAL_TASK,
  	);
	$items['raids/players'] = array(
	    'title' => t('Players'),
		'description' => 'Nextpls Raidtracker helps you to track your Raids.',
		'access arguments' => array('access nprt'),
		'file'	=> 'nprt.pages.inc',
		'page callback' => 'nprt_player_page',
		'type' => MENU_LOCAL_TASK,
  	);

	$items['admin/settings/nprt'] = array(
	    'title' => 'Nextpls Raidtracker',
	    'description' => 'Nextpls Raidtracker Administration.',
	    'page arguments' => array('nprt_admin_report_imported_raids_form'),
		'page callback' => 'drupal_get_form',
	    'access arguments' => array('administer nprt'),
	    'file' => 'nprt.admin.inc',
  	);
   	$items['admin/settings/nprt/raids'] = array(
	    'title' => 'Overview',
	    'type' => MENU_DEFAULT_LOCAL_TASK,
	    'weight' => -10,
  	);
  	$items['admin/nprt/raidinfo/get/%'] = array(
        'access arguments' => array('administer nprt'),
  		'page arguments' => array('nprt_admin_report_raidinfo', 1),
  		'page callback' => 'nprt_admin_report_raidinfo',
  		'type' => MENU_CALLBACK,
  		'file' => 'nprt.admin.inc',
    );
	return $items;
}

 
function nprt_theme() {
   return array(
      'nprt_javascript' => array(
         'arguments' => array(),
      ),
      'nprt_stylesheet' => array(
         'arguments' => array(),
      ),
      'nprt_ajax' => array(
      		'template' => 'ajax',
      		'arguments' => array(
        		'content' => NULL,
      	),
      ),
      'tablesort_pager' => array(
      	'template' => 'templates/tablesort_pager',
      	'arguments'	=>	array()
      ),
   );   
}

function nprt_init() {
  theme('nprt_javascript');
  theme('nprt_stylesheet');
}

function theme_nprt_javascript() {
  drupal_add_js(drupal_get_path('module', 'nprt').'/js/jquery.tablesorter.min.js');
  drupal_add_js(drupal_get_path('module', 'nprt').'/js/jquery.tablesorter.pager.js');
  drupal_add_js(drupal_get_path('module', 'nprt').'/js/jquery.tablesorter.filter.js');
  drupal_add_js(drupal_get_path('module', 'nprt').'/js/nprt.js');
}

function theme_nprt_stylesheet() {
  drupal_add_css(drupal_get_path('module', 'nprt').'/css/nprt.css');
}